language: node_js
node_js:
  - 0.10.15
env:
  global:
  - VERSION_NUMBER="`git describe --tags | sed 's/^[a-z,A-Z]*//'`"
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
